# -*- coding: utf-8 -*-

#
# Copyright (c) 2017-present, SefaMerve R&D Center
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(723, 709)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 681, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditModelFile = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditModelFile.setObjectName("lineEditModelFile")
        self.horizontalLayout_3.addWidget(self.lineEditModelFile)
        self.toolButtonModelFile = QtGui.QToolButton(self.layoutWidget)
        self.toolButtonModelFile.setObjectName("toolButtonModelFile")
        self.horizontalLayout_3.addWidget(self.toolButtonModelFile)
        self.layoutWidget_2 = QtGui.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(180, 140, 181, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEditLRUpdate = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditLRUpdate.setObjectName("lineEditLRUpdate")
        self.horizontalLayout_5.addWidget(self.lineEditLRUpdate)
        self.layoutWidget_3 = QtGui.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(390, 140, 111, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEditEpoch = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditEpoch.setObjectName("lineEditEpoch")
        self.horizontalLayout_6.addWidget(self.lineEditEpoch)
        self.layoutWidget_4 = QtGui.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(290, 180, 133, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(self.layoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEditWordNgrams = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditWordNgrams.setObjectName("lineEditWordNgrams")
        self.horizontalLayout_7.addWidget(self.lineEditWordNgrams)
        self.layoutWidget_5 = QtGui.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 220, 149, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtGui.QLabel(self.layoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEditContextWindow = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditContextWindow.setObjectName("lineEditContextWindow")
        self.horizontalLayout_8.addWidget(self.lineEditContextWindow)
        self.layoutWidget_6 = QtGui.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(520, 140, 182, 22))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtGui.QLabel(self.layoutWidget_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEditDim = QtGui.QLineEdit(self.layoutWidget_6)
        self.lineEditDim.setObjectName("lineEditDim")
        self.horizontalLayout_9.addWidget(self.lineEditDim)
        self.layoutWidget_7 = QtGui.QWidget(Dialog)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 180, 251, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtGui.QLabel(self.layoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBoxLoss = QtGui.QComboBox(self.layoutWidget_7)
        self.comboBoxLoss.setObjectName("comboBoxLoss")
        self.horizontalLayout_10.addWidget(self.comboBoxLoss)
        self.layoutWidget_8 = QtGui.QWidget(Dialog)
        self.layoutWidget_8.setGeometry(QtCore.QRect(480, 180, 208, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtGui.QLabel(self.layoutWidget_8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.lineEditNeg = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEditNeg.setObjectName("lineEditNeg")
        self.horizontalLayout_12.addWidget(self.lineEditNeg)
        self.layoutWidget_9 = QtGui.QWidget(Dialog)
        self.layoutWidget_9.setGeometry(QtCore.QRect(200, 220, 149, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtGui.QLabel(self.layoutWidget_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lineEditMinWord = QtGui.QLineEdit(self.layoutWidget_9)
        self.lineEditMinWord.setObjectName("lineEditMinWord")
        self.horizontalLayout_13.addWidget(self.lineEditMinWord)
        self.layoutWidget_10 = QtGui.QWidget(Dialog)
        self.layoutWidget_10.setGeometry(QtCore.QRect(370, 220, 149, 22))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtGui.QLabel(self.layoutWidget_10)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lineEditMinLabel = QtGui.QLineEdit(self.layoutWidget_10)
        self.lineEditMinLabel.setObjectName("lineEditMinLabel")
        self.horizontalLayout_14.addWidget(self.lineEditMinLabel)
        self.layoutWidget_11 = QtGui.QWidget(Dialog)
        self.layoutWidget_11.setGeometry(QtCore.QRect(540, 260, 108, 24))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtGui.QLabel(self.layoutWidget_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEditThreads = QtGui.QLineEdit(self.layoutWidget_11)
        self.lineEditThreads.setObjectName("lineEditThreads")
        self.horizontalLayout_15.addWidget(self.lineEditThreads)
        self.layoutWidget_12 = QtGui.QWidget(Dialog)
        self.layoutWidget_12.setGeometry(QtCore.QRect(540, 220, 149, 22))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtGui.QLabel(self.layoutWidget_12)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.lineEditThreshold = QtGui.QLineEdit(self.layoutWidget_12)
        self.lineEditThreshold.setObjectName("lineEditThreshold")
        self.horizontalLayout_16.addWidget(self.lineEditThreshold)
        self.layoutWidget_13 = QtGui.QWidget(Dialog)
        self.layoutWidget_13.setGeometry(QtCore.QRect(20, 260, 149, 22))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtGui.QLabel(self.layoutWidget_13)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.lineEditBucket = QtGui.QLineEdit(self.layoutWidget_13)
        self.lineEditBucket.setObjectName("lineEditBucket")
        self.horizontalLayout_17.addWidget(self.lineEditBucket)
        self.layoutWidget_14 = QtGui.QWidget(Dialog)
        self.layoutWidget_14.setGeometry(QtCore.QRect(370, 260, 149, 22))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtGui.QLabel(self.layoutWidget_14)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.lineEditMaxCharNG = QtGui.QLineEdit(self.layoutWidget_14)
        self.lineEditMaxCharNG.setObjectName("lineEditMaxCharNG")
        self.horizontalLayout_18.addWidget(self.lineEditMaxCharNG)
        self.layoutWidget_15 = QtGui.QWidget(Dialog)
        self.layoutWidget_15.setGeometry(QtCore.QRect(200, 260, 153, 22))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtGui.QLabel(self.layoutWidget_15)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.lineEditMinCharNG = QtGui.QLineEdit(self.layoutWidget_15)
        self.lineEditMinCharNG.setObjectName("lineEditMinCharNG")
        self.horizontalLayout_19.addWidget(self.lineEditMinCharNG)
        self.pushButtonRun = QtGui.QPushButton(Dialog)
        self.pushButtonRun.setGeometry(QtCore.QRect(580, 10, 60, 40))
        self.pushButtonRun.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRun.setIcon(icon)
        self.pushButtonRun.setIconSize(QtCore.QSize(60, 40))
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 300, 681, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 340, 701, 361))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 671, 321))
        self.listWidget.setObjectName("listWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButtonZoom = QtGui.QPushButton(self.tab_2)
        self.pushButtonZoom.setGeometry(QtCore.QRect(10, 10, 32, 32))
        self.pushButtonZoom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonZoom.setIcon(icon1)
        self.pushButtonZoom.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonZoom.setObjectName("pushButtonZoom")
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 271, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBoxCommand = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxCommand.setObjectName("comboBoxCommand")
        self.horizontalLayout.addWidget(self.comboBoxCommand)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 681, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditTextFile = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditTextFile.setObjectName("lineEditTextFile")
        self.horizontalLayout_2.addWidget(self.lineEditTextFile)
        self.toolButtonTextFile = QtGui.QToolButton(self.layoutWidget2)
        self.toolButtonTextFile.setObjectName("toolButtonTextFile")
        self.horizontalLayout_2.addWidget(self.toolButtonTextFile)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 140, 141, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditLR = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditLR.setToolTip("")
        self.lineEditLR.setObjectName("lineEditLR")
        self.horizontalLayout_4.addWidget(self.lineEditLR)
        self.pushButtonStop = QtGui.QPushButton(Dialog)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setGeometry(QtCore.QRect(650, 10, 60, 40))
        self.pushButtonStop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStop.setIcon(icon2)
        self.pushButtonStop.setIconSize(QtCore.QSize(60, 38))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(320, 20, 211, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.comboBoxMode = QtGui.QComboBox(self.widget)
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.horizontalLayout_11.addWidget(self.comboBoxMode)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "FastText GUI ( Sefamerve R&D Center )", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Model File:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditModelFile.setToolTip(QtGui.QApplication.translate("Dialog", "model file name or pretrained model file", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditModelFile.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonModelFile.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Learning Rate Update :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditLRUpdate.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Epoch :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditEpoch.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Word NGrams", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditWordNgrams.setToolTip(QtGui.QApplication.translate("Dialog", "max length of word ngram", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditWordNgrams.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Context Window :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditContextWindow.setToolTip(QtGui.QApplication.translate("Dialog", "size of the context window", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditContextWindow.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Word Vector Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditDim.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Loss Function  :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Number of negatives sampled:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNeg.setToolTip(QtGui.QApplication.translate("Dialog", "number of negatives sampled", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNeg.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Min count word:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinWord.setToolTip(QtGui.QApplication.translate("Dialog", "minimal number of word occurences", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinWord.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Min count label :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinLabel.setToolTip(QtGui.QApplication.translate("Dialog", "minimal number of label occurences", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinLabel.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Threads :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditThreads.setToolTip(QtGui.QApplication.translate("Dialog", "number of thread", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditThreads.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Threshold :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditThreshold.setToolTip(QtGui.QApplication.translate("Dialog", "sampling threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditThreshold.setText(QtGui.QApplication.translate("Dialog", "0.0001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Bucket :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditBucket.setToolTip(QtGui.QApplication.translate("Dialog", "number of buckets", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditBucket.setText(QtGui.QApplication.translate("Dialog", "2000000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Max char NGram :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMaxCharNG.setToolTip(QtGui.QApplication.translate("Dialog", "max length of char ngram", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMaxCharNG.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Min char NGram :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinCharNG.setToolTip(QtGui.QApplication.translate("Dialog", "min length of char ngram", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMinCharNG.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Command :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Text File:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTextFile.setToolTip(QtGui.QApplication.translate("Dialog", "input text  file or corpus file", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTextFile.setText(QtGui.QApplication.translate("Dialog", "", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonTextFile.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Learning Rate :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditLR.setText(QtGui.QApplication.translate("Dialog", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Run Mode :", None, QtGui.QApplication.UnicodeUTF8))

